base_local_planner: nav_core_adapter::LocalPlannerAdapter

LocalPlannerAdapter:
  planner_name: dwb_local_planner::DWBLocalPlanner
  
DWBLocalPlanner:
  debug_trajectory_details: True
  min_vel_x: 0.0
  min_vel_y: 0.0
  max_vel_x: 1.00
  max_vel_y: 0.0
  max_vel_theta: 1.05
  min_speed_xy: 0.0
  max_speed_xy: 1.00
  min_speed_theta: 0.0
  acc_lim_x: 0.6
  acc_lim_y: 0.0
  acc_lim_theta: 3.14
  decel_lim_x: -2.5
  decel_lim_y: 0.0
  decel_lim_theta: -3.14
  vx_samples: 20
  vy_samples: 5
  vtheta_samples: 20
  sim_time: 1.7
  linear_granularity: 0.05
  angular_granularity: 0.025
  transform_tolerance: 0.2
  xy_goal_tolerance: 0.25
  trans_stopped_velocity: 0.25
  short_circuit_trajectory_evaluation: True
  stateful: True
  critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
  BaseObstacle.scale: 0.04
  PathAlign.scale: 12.0
  PathAlign.forward_point_distance: 0.1
  GoalAlign.scale: 7.0
  GoalAlign.forward_point_distance: 0.1
  PathDist.scale: 32.0
  GoalDist.scale: 24.0
  RotateToGoal.scale: 32.0
  RotateToGoal.slowing_factor: 5.0
  RotateToGoal.lookahead_time: -1.0
