// Generated by gencpp from file pal_detection_msgs/FaceThermalDetections.msg
// DO NOT EDIT!


#ifndef PAL_DETECTION_MSGS_MESSAGE_FACETHERMALDETECTIONS_H
#define PAL_DETECTION_MSGS_MESSAGE_FACETHERMALDETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/RegionOfInterest.h>

namespace pal_detection_msgs
{
template <class ContainerAllocator>
struct FaceThermalDetections_
{
  typedef FaceThermalDetections_<ContainerAllocator> Type;

  FaceThermalDetections_()
    : header()
    , faces()  {
    }
  FaceThermalDetections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , faces(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::sensor_msgs::RegionOfInterest_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sensor_msgs::RegionOfInterest_<ContainerAllocator> >> _faces_type;
  _faces_type faces;





  typedef boost::shared_ptr< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> const> ConstPtr;

}; // struct FaceThermalDetections_

typedef ::pal_detection_msgs::FaceThermalDetections_<std::allocator<void> > FaceThermalDetections;

typedef boost::shared_ptr< ::pal_detection_msgs::FaceThermalDetections > FaceThermalDetectionsPtr;
typedef boost::shared_ptr< ::pal_detection_msgs::FaceThermalDetections const> FaceThermalDetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator1> & lhs, const ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.faces == rhs.faces;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator1> & lhs, const ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_detection_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa2af80db62cfc8ff93c82f9846f3ebf";
  }

  static const char* value(const ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa2af80db62cfc8fULL;
  static const uint64_t static_value2 = 0xf93c82f9846f3ebfULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_detection_msgs/FaceThermalDetections";
  }

  static const char* value(const ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"sensor_msgs/RegionOfInterest[]  faces\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
;
  }

  static const char* value(const ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.faces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceThermalDetections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_detection_msgs::FaceThermalDetections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "faces[]" << std::endl;
    for (size_t i = 0; i < v.faces.size(); ++i)
    {
      s << indent << "  faces[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::RegionOfInterest_<ContainerAllocator> >::stream(s, indent + "    ", v.faces[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_DETECTION_MSGS_MESSAGE_FACETHERMALDETECTIONS_H
