// Generated by gencpp from file pal_detection_msgs/Recognizer.msg
// DO NOT EDIT!


#ifndef PAL_DETECTION_MSGS_MESSAGE_RECOGNIZER_H
#define PAL_DETECTION_MSGS_MESSAGE_RECOGNIZER_H

#include <ros/service_traits.h>


#include <pal_detection_msgs/RecognizerRequest.h>
#include <pal_detection_msgs/RecognizerResponse.h>


namespace pal_detection_msgs
{

struct Recognizer
{

typedef RecognizerRequest Request;
typedef RecognizerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Recognizer
} // namespace pal_detection_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_detection_msgs::Recognizer > {
  static const char* value()
  {
    return "1988e71091b2db6d28fdeea96cff5fb1";
  }

  static const char* value(const ::pal_detection_msgs::Recognizer&) { return value(); }
};

template<>
struct DataType< ::pal_detection_msgs::Recognizer > {
  static const char* value()
  {
    return "pal_detection_msgs/Recognizer";
  }

  static const char* value(const ::pal_detection_msgs::Recognizer&) { return value(); }
};


// service_traits::MD5Sum< ::pal_detection_msgs::RecognizerRequest> should match
// service_traits::MD5Sum< ::pal_detection_msgs::Recognizer >
template<>
struct MD5Sum< ::pal_detection_msgs::RecognizerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_detection_msgs::Recognizer >::value();
  }
  static const char* value(const ::pal_detection_msgs::RecognizerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_detection_msgs::RecognizerRequest> should match
// service_traits::DataType< ::pal_detection_msgs::Recognizer >
template<>
struct DataType< ::pal_detection_msgs::RecognizerRequest>
{
  static const char* value()
  {
    return DataType< ::pal_detection_msgs::Recognizer >::value();
  }
  static const char* value(const ::pal_detection_msgs::RecognizerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_detection_msgs::RecognizerResponse> should match
// service_traits::MD5Sum< ::pal_detection_msgs::Recognizer >
template<>
struct MD5Sum< ::pal_detection_msgs::RecognizerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_detection_msgs::Recognizer >::value();
  }
  static const char* value(const ::pal_detection_msgs::RecognizerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_detection_msgs::RecognizerResponse> should match
// service_traits::DataType< ::pal_detection_msgs::Recognizer >
template<>
struct DataType< ::pal_detection_msgs::RecognizerResponse>
{
  static const char* value()
  {
    return DataType< ::pal_detection_msgs::Recognizer >::value();
  }
  static const char* value(const ::pal_detection_msgs::RecognizerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_DETECTION_MSGS_MESSAGE_RECOGNIZER_H
