; Auto-generated. Do not edit!


(cl:in-package pal_navigation_msgs-msg)


;//! \htmlinclude JoyPriorityFeedback.msg.html

(cl:defclass <JoyPriorityFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass JoyPriorityFeedback (<JoyPriorityFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JoyPriorityFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JoyPriorityFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pal_navigation_msgs-msg:<JoyPriorityFeedback> is deprecated: use pal_navigation_msgs-msg:JoyPriorityFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JoyPriorityFeedback>) ostream)
  "Serializes a message object of type '<JoyPriorityFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JoyPriorityFeedback>) istream)
  "Deserializes a message object of type '<JoyPriorityFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JoyPriorityFeedback>)))
  "Returns string type for a message object of type '<JoyPriorityFeedback>"
  "pal_navigation_msgs/JoyPriorityFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JoyPriorityFeedback)))
  "Returns string type for a message object of type 'JoyPriorityFeedback"
  "pal_navigation_msgs/JoyPriorityFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JoyPriorityFeedback>)))
  "Returns md5sum for a message object of type '<JoyPriorityFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JoyPriorityFeedback)))
  "Returns md5sum for a message object of type 'JoyPriorityFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JoyPriorityFeedback>)))
  "Returns full string definition for message of type '<JoyPriorityFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JoyPriorityFeedback)))
  "Returns full string definition for message of type 'JoyPriorityFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JoyPriorityFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JoyPriorityFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'JoyPriorityFeedback
))
