; Auto-generated. Do not edit!


(cl:in-package pal_navigation_msgs-msg)


;//! \htmlinclude JoyPriorityResult.msg.html

(cl:defclass <JoyPriorityResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass JoyPriorityResult (<JoyPriorityResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JoyPriorityResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JoyPriorityResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pal_navigation_msgs-msg:<JoyPriorityResult> is deprecated: use pal_navigation_msgs-msg:JoyPriorityResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JoyPriorityResult>) ostream)
  "Serializes a message object of type '<JoyPriorityResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JoyPriorityResult>) istream)
  "Deserializes a message object of type '<JoyPriorityResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JoyPriorityResult>)))
  "Returns string type for a message object of type '<JoyPriorityResult>"
  "pal_navigation_msgs/JoyPriorityResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JoyPriorityResult)))
  "Returns string type for a message object of type 'JoyPriorityResult"
  "pal_navigation_msgs/JoyPriorityResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JoyPriorityResult>)))
  "Returns md5sum for a message object of type '<JoyPriorityResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JoyPriorityResult)))
  "Returns md5sum for a message object of type 'JoyPriorityResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JoyPriorityResult>)))
  "Returns full string definition for message of type '<JoyPriorityResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JoyPriorityResult)))
  "Returns full string definition for message of type 'JoyPriorityResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JoyPriorityResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JoyPriorityResult>))
  "Converts a ROS message object to a list"
  (cl:list 'JoyPriorityResult
))
