(cl:defpackage pal_common_msgs-srv
  (:use )
  (:export
   "GETSTRING"
   "<GETSTRING-REQUEST>"
   "GETSTRING-REQUEST"
   "<GETSTRING-RESPONSE>"
   "GETSTRING-RESPONSE"
   "SETSTRING"
   "<SETSTRING-REQUEST>"
   "SETSTRING-REQUEST"
   "<SETSTRING-RESPONSE>"
   "SETSTRING-RESPONSE"
  ))

