; Auto-generated. Do not edit!


(cl:in-package pal_navigation_msgs-msg)


;//! \htmlinclude FollowWaypointsResult.msg.html

(cl:defclass <FollowWaypointsResult> (roslisp-msg-protocol:ros-message)
  ((missed_waypoints
    :reader missed_waypoints
    :initarg :missed_waypoints
    :type (cl:vector pal_navigation_msgs-msg:MissedWaypoint)
   :initform (cl:make-array 0 :element-type 'pal_navigation_msgs-msg:MissedWaypoint :initial-element (cl:make-instance 'pal_navigation_msgs-msg:MissedWaypoint))))
)

(cl:defclass FollowWaypointsResult (<FollowWaypointsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowWaypointsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowWaypointsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pal_navigation_msgs-msg:<FollowWaypointsResult> is deprecated: use pal_navigation_msgs-msg:FollowWaypointsResult instead.")))

(cl:ensure-generic-function 'missed_waypoints-val :lambda-list '(m))
(cl:defmethod missed_waypoints-val ((m <FollowWaypointsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pal_navigation_msgs-msg:missed_waypoints-val is deprecated.  Use pal_navigation_msgs-msg:missed_waypoints instead.")
  (missed_waypoints m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowWaypointsResult>) ostream)
  "Serializes a message object of type '<FollowWaypointsResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'missed_waypoints))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'missed_waypoints))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowWaypointsResult>) istream)
  "Deserializes a message object of type '<FollowWaypointsResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'missed_waypoints) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'missed_waypoints)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'pal_navigation_msgs-msg:MissedWaypoint))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowWaypointsResult>)))
  "Returns string type for a message object of type '<FollowWaypointsResult>"
  "pal_navigation_msgs/FollowWaypointsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowWaypointsResult)))
  "Returns string type for a message object of type 'FollowWaypointsResult"
  "pal_navigation_msgs/FollowWaypointsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowWaypointsResult>)))
  "Returns md5sum for a message object of type '<FollowWaypointsResult>"
  "a001ea894e996455eb93e1c0139428c3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowWaypointsResult)))
  "Returns md5sum for a message object of type 'FollowWaypointsResult"
  "a001ea894e996455eb93e1c0139428c3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowWaypointsResult>)))
  "Returns full string definition for message of type '<FollowWaypointsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%pal_navigation_msgs/MissedWaypoint[] missed_waypoints~%~%================================================================================~%MSG: pal_navigation_msgs/MissedWaypoint~%uint32 index~%geometry_msgs/PoseStamped goal~%uint16 error_code~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowWaypointsResult)))
  "Returns full string definition for message of type 'FollowWaypointsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%pal_navigation_msgs/MissedWaypoint[] missed_waypoints~%~%================================================================================~%MSG: pal_navigation_msgs/MissedWaypoint~%uint32 index~%geometry_msgs/PoseStamped goal~%uint16 error_code~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowWaypointsResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'missed_waypoints) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowWaypointsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowWaypointsResult
    (cl:cons ':missed_waypoints (missed_waypoints msg))
))
