# Independent settings for the local costmap
local_costmap:
  # attention, the order and combination method matters
  plugins:
    - name: obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: obstacle_sonar_layer
      type: 'range_sensor_layer::RangeSensorLayer'
    - name: static_vo_layer
      type: 'costmap_2d::StaticLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'
