; Auto-generated. Do not edit!


(cl:in-package pal_common_msgs-msg)


;//! \htmlinclude DisableFeedback.msg.html

(cl:defclass <DisableFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DisableFeedback (<DisableFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DisableFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DisableFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pal_common_msgs-msg:<DisableFeedback> is deprecated: use pal_common_msgs-msg:DisableFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DisableFeedback>) ostream)
  "Serializes a message object of type '<DisableFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DisableFeedback>) istream)
  "Deserializes a message object of type '<DisableFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DisableFeedback>)))
  "Returns string type for a message object of type '<DisableFeedback>"
  "pal_common_msgs/DisableFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DisableFeedback)))
  "Returns string type for a message object of type 'DisableFeedback"
  "pal_common_msgs/DisableFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DisableFeedback>)))
  "Returns md5sum for a message object of type '<DisableFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DisableFeedback)))
  "Returns md5sum for a message object of type 'DisableFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DisableFeedback>)))
  "Returns full string definition for message of type '<DisableFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DisableFeedback)))
  "Returns full string definition for message of type 'DisableFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DisableFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DisableFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DisableFeedback
))
