# voxel_costmap.yaml
global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  resolution: 0.1
  width: 10.0
  height: 10.0
  origin_x: -5.0
  origin_y: -5.0
  plugins:
    - VoxelCostmapPlugin:
        frame: /xtion_depth_frame
        topic: /xtion/depth_registered/points
        voxel_size: 0.1
        height: 2.0  # Adjust based on the expected height of obstacles
        width: 2.0   # Adjust as needed
        resolution: 0.1
    - LaserScanCostmapPlugin:  # Add this plugin for laser scan data
        frame: /base_link  # Adjust frame according to your setup
        topic: /scan
        obstacle_range: 2.5        # Maximum range for laser
        raytrace_range: 3.0         # Range to raytrace
