#action to perform
string INPUT_ACCEPT = INPUT_ACCEPT
string INPUT_REJECT = INPUT_REJECT
string INPUT_CANCEL = INPUT_CANCEL

# Deprecated in favor of the INPUT_* above. Will be removed in a future message
string OK = ok
string YES = yes
string NO = no
string CANCEL = cancel
string ABORT = abort

# Can be any of the above, and additionally any custom action you want
string action

InputArgument[] args
