// Generated by gencpp from file pal_interaction_msgs/ASRActivation.msg
// DO NOT EDIT!


#ifndef PAL_INTERACTION_MSGS_MESSAGE_ASRACTIVATION_H
#define PAL_INTERACTION_MSGS_MESSAGE_ASRACTIVATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_interaction_msgs
{
template <class ContainerAllocator>
struct ASRActivation_
{
  typedef ASRActivation_<ContainerAllocator> Type;

  ASRActivation_()
    : action(0)  {
    }
  ASRActivation_(const ContainerAllocator& _alloc)
    : action(0)  {
  (void)_alloc;
    }



   typedef int8_t _action_type;
  _action_type action;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ACTIVATE)
  #undef ACTIVATE
#endif
#if defined(_WIN32) && defined(DEACTIVATE)
  #undef DEACTIVATE
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif
#if defined(_WIN32) && defined(RESUME)
  #undef RESUME
#endif
#if defined(_WIN32) && defined(CALIBRATE)
  #undef CALIBRATE
#endif

  enum {
    ACTIVATE = 1,
    DEACTIVATE = 2,
    PAUSE = 3,
    RESUME = 4,
    CALIBRATE = 5,
  };


  typedef boost::shared_ptr< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> const> ConstPtr;

}; // struct ASRActivation_

typedef ::pal_interaction_msgs::ASRActivation_<std::allocator<void> > ASRActivation;

typedef boost::shared_ptr< ::pal_interaction_msgs::ASRActivation > ASRActivationPtr;
typedef boost::shared_ptr< ::pal_interaction_msgs::ASRActivation const> ASRActivationConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_interaction_msgs::ASRActivation_<ContainerAllocator1> & lhs, const ::pal_interaction_msgs::ASRActivation_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_interaction_msgs::ASRActivation_<ContainerAllocator1> & lhs, const ::pal_interaction_msgs::ASRActivation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_interaction_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbd42ef6448061151159fe3a848b2553";
  }

  static const char* value(const ::pal_interaction_msgs::ASRActivation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbd42ef644806115ULL;
  static const uint64_t static_value2 = 0x1159fe3a848b2553ULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_interaction_msgs/ASRActivation";
  }

  static const char* value(const ::pal_interaction_msgs::ASRActivation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message that can be used to send activation commands to the speech recognizer.\n"
"# It is possible to activate/deactivate or pause/resume the recognizer with these commands.\n"
"# action list\n"
"int8 ACTIVATE = 1\n"
"int8 DEACTIVATE = 2\n"
"int8 PAUSE = 3\n"
"int8 RESUME = 4\n"
"int8 CALIBRATE = 5\n"
"\n"
"# Message variables\n"
"int8 action\n"
"\n"
;
  }

  static const char* value(const ::pal_interaction_msgs::ASRActivation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ASRActivation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_interaction_msgs::ASRActivation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_interaction_msgs::ASRActivation_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<int8_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_INTERACTION_MSGS_MESSAGE_ASRACTIVATION_H
