// Generated by gencpp from file pal_interaction_msgs/ASRService.msg
// DO NOT EDIT!


#ifndef PAL_INTERACTION_MSGS_MESSAGE_ASRSERVICE_H
#define PAL_INTERACTION_MSGS_MESSAGE_ASRSERVICE_H

#include <ros/service_traits.h>


#include <pal_interaction_msgs/ASRServiceRequest.h>
#include <pal_interaction_msgs/ASRServiceResponse.h>


namespace pal_interaction_msgs
{

struct ASRService
{

typedef ASRServiceRequest Request;
typedef ASRServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ASRService
} // namespace pal_interaction_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_interaction_msgs::ASRService > {
  static const char* value()
  {
    return "f43b49712181a29a41dc6f7687806c53";
  }

  static const char* value(const ::pal_interaction_msgs::ASRService&) { return value(); }
};

template<>
struct DataType< ::pal_interaction_msgs::ASRService > {
  static const char* value()
  {
    return "pal_interaction_msgs/ASRService";
  }

  static const char* value(const ::pal_interaction_msgs::ASRService&) { return value(); }
};


// service_traits::MD5Sum< ::pal_interaction_msgs::ASRServiceRequest> should match
// service_traits::MD5Sum< ::pal_interaction_msgs::ASRService >
template<>
struct MD5Sum< ::pal_interaction_msgs::ASRServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_interaction_msgs::ASRService >::value();
  }
  static const char* value(const ::pal_interaction_msgs::ASRServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_interaction_msgs::ASRServiceRequest> should match
// service_traits::DataType< ::pal_interaction_msgs::ASRService >
template<>
struct DataType< ::pal_interaction_msgs::ASRServiceRequest>
{
  static const char* value()
  {
    return DataType< ::pal_interaction_msgs::ASRService >::value();
  }
  static const char* value(const ::pal_interaction_msgs::ASRServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_interaction_msgs::ASRServiceResponse> should match
// service_traits::MD5Sum< ::pal_interaction_msgs::ASRService >
template<>
struct MD5Sum< ::pal_interaction_msgs::ASRServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_interaction_msgs::ASRService >::value();
  }
  static const char* value(const ::pal_interaction_msgs::ASRServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_interaction_msgs::ASRServiceResponse> should match
// service_traits::DataType< ::pal_interaction_msgs::ASRService >
template<>
struct DataType< ::pal_interaction_msgs::ASRServiceResponse>
{
  static const char* value()
  {
    return DataType< ::pal_interaction_msgs::ASRService >::value();
  }
  static const char* value(const ::pal_interaction_msgs::ASRServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_INTERACTION_MSGS_MESSAGE_ASRSERVICE_H
