// Generated by gencpp from file pal_motion_model_msgs/GetMotionMapResponse.msg
// DO NOT EDIT!


#ifndef PAL_MOTION_MODEL_MSGS_MESSAGE_GETMOTIONMAPRESPONSE_H
#define PAL_MOTION_MODEL_MSGS_MESSAGE_GETMOTIONMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pal_motion_model_msgs/MotionModelMap.h>

namespace pal_motion_model_msgs
{
template <class ContainerAllocator>
struct GetMotionMapResponse_
{
  typedef GetMotionMapResponse_<ContainerAllocator> Type;

  GetMotionMapResponse_()
    : map()  {
    }
  GetMotionMapResponse_(const ContainerAllocator& _alloc)
    : map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::pal_motion_model_msgs::MotionModelMap_<ContainerAllocator>  _map_type;
  _map_type map;





  typedef boost::shared_ptr< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMotionMapResponse_

typedef ::pal_motion_model_msgs::GetMotionMapResponse_<std::allocator<void> > GetMotionMapResponse;

typedef boost::shared_ptr< ::pal_motion_model_msgs::GetMotionMapResponse > GetMotionMapResponsePtr;
typedef boost::shared_ptr< ::pal_motion_model_msgs::GetMotionMapResponse const> GetMotionMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator1> & lhs, const ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.map == rhs.map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator1> & lhs, const ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_motion_model_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff508f86b1d484eed7ca1c596036d1bf";
  }

  static const char* value(const ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff508f86b1d484eeULL;
  static const uint64_t static_value2 = 0xd7ca1c596036d1bfULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_motion_model_msgs/GetMotionMapResponse";
  }

  static const char* value(const ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_motion_model_msgs/MotionModelMap map\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pal_motion_model_msgs/MotionModelMap\n"
"#This represents a 2-D motion model map, in which each cell has the probabilistic motion models for the robot.\n"
"\n"
"Header header \n"
"\n"
"#MetaData for the map\n"
"nav_msgs/MapMetaData info\n"
"\n"
"# The map data, in row-major order, starting with (0,0). A list of  models is stored for every cell. \n"
"MotionModelList[] data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: pal_motion_model_msgs/MotionModelList\n"
"#list of motion models learnt in a specific place\n"
"\n"
"MotionModel[] models\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pal_motion_model_msgs/MotionModel\n"
"## Contains the 2D motion model of a robot at a specific location\n"
"\n"
"#Heading direction is represented through a gaussian pdf.\n"
"float32  heading_mean\n"
"float32  heading_std_dev\n"
"\n"
"#For statistics we store a pdf over the robot speeds\n"
"float32  linear_speed_mean\n"
"float32  linear_speed_std_dev\n"
"float32  angular_speed_mean\n"
"float32  angular_speed_std_dev\n"
"\n"
;
  }

  static const char* value(const ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMotionMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_motion_model_msgs::GetMotionMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "map: ";
    s << std::endl;
    Printer< ::pal_motion_model_msgs::MotionModelMap_<ContainerAllocator> >::stream(s, indent + "  ", v.map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_MOTION_MODEL_MSGS_MESSAGE_GETMOTIONMAPRESPONSE_H
