; Auto-generated. Do not edit!


(cl:in-package pal_behaviour_msgs-msg)


;//! \htmlinclude PresentationGoal.msg.html

(cl:defclass <PresentationGoal> (roslisp-msg-protocol:ros-message)
  ((presentationFile
    :reader presentationFile
    :initarg :presentationFile
    :type cl:string
    :initform ""))
)

(cl:defclass PresentationGoal (<PresentationGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PresentationGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PresentationGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pal_behaviour_msgs-msg:<PresentationGoal> is deprecated: use pal_behaviour_msgs-msg:PresentationGoal instead.")))

(cl:ensure-generic-function 'presentationFile-val :lambda-list '(m))
(cl:defmethod presentationFile-val ((m <PresentationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pal_behaviour_msgs-msg:presentationFile-val is deprecated.  Use pal_behaviour_msgs-msg:presentationFile instead.")
  (presentationFile m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PresentationGoal>) ostream)
  "Serializes a message object of type '<PresentationGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'presentationFile))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'presentationFile))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PresentationGoal>) istream)
  "Deserializes a message object of type '<PresentationGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'presentationFile) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'presentationFile) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PresentationGoal>)))
  "Returns string type for a message object of type '<PresentationGoal>"
  "pal_behaviour_msgs/PresentationGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PresentationGoal)))
  "Returns string type for a message object of type 'PresentationGoal"
  "pal_behaviour_msgs/PresentationGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PresentationGoal>)))
  "Returns md5sum for a message object of type '<PresentationGoal>"
  "2fabda36f289edf937fcb83c63997aa0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PresentationGoal)))
  "Returns md5sum for a message object of type 'PresentationGoal"
  "2fabda36f289edf937fcb83c63997aa0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PresentationGoal>)))
  "Returns full string definition for message of type '<PresentationGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string presentationFile~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PresentationGoal)))
  "Returns full string definition for message of type 'PresentationGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string presentationFile~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PresentationGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'presentationFile))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PresentationGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PresentationGoal
    (cl:cons ':presentationFile (presentationFile msg))
))
