(cl:in-package pal_vision_msgs-msg)
(cl:export '(IMAGEBOUNDINGBOX-VAL
          IMAGEBOUNDINGBOX
          DIRECTION-VAL
          DIRECTION
          HOG-VAL
          HOG
          PRINCIPALEIGENVECTORRGB-VAL
          PRINCIPALEIGENVECTORRGB
          RGBCLUSTERCENTERS-VAL
          RGBCLUSTERCENTERS
          RGBDESCRIPTOR1-VAL
          RGBDESCRIPTOR1
          RGBDESCRIPTOR2-VAL
          RGBDESCRIPTOR2
))