# Independent settings for the planner's costmap
global_costmap:
  # attention, the order and combination method matters
  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: front_obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: rear_obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: ramp_layer
      type: 'polycost::PolyCostLayer'
    - name: static_highway_layer
      type: 'costmap_2d::StaticLayer'
    - name: static_vo_layer
      type: 'costmap_2d::StaticLayer'
    - name: obstacle_rgbd_layer
      type: 'spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'
