# Independent settings for the local costmap
local_costmap:
  # attention, the order and combination method matters
  plugins:
    - name: front_obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: rear_obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: pointcloud_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: static_vo_layer
      type: 'costmap_2d::StaticLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'
